### ISSUE TITLE
Add method to build/publish oci's without devtools

### ISSUE THREAD

**Issue by AtzeDeVries** [coopnorge/github-workflow-devtools-build-oci#5]

**Comment by nhhagen** [comment]
@AtzeDeVries do you have any more details on this? What are we trying to achieve?

**Comment by AtzeDeVries** [comment]
I thought we could use this workflow by just providing a Dockerfile and tag-pattern and it will build/push the image. 

We also discussed using a devtools workflow which just builds plain images, this then could be directly used by this workflow. I kinda feel the first suggestion will be simpler for most end users, but a bit defiant of the ways of working. @nhhagen What do you think?

**Comment by nhhagen** [comment]
To stay with our current ways we should probably create a simple devtools image that will build a provided `Dockerfile`. That way the workflow just operate on devtools and does not contain to paths.

We have not been to keep and happy with implementing details of CI using GitHub Actions as there is no way of running this locally.

**Comment by AtzeDeVries** [comment]
true, for plain docker images we still need CI, so providing that using devtools would be best. Lets close this.
